DROP TABLE IF EXISTS books CASCADE;

CREATE TABLE books (
    id SERIAL PRIMARY KEY NOT NULL,
	title VARCHAR(255) NOT NULL,
	author VARCHAR(255) NOT NULL,
    genre VARCHAR(255) NOT NULL,
	isbn VARCHAR NOT NULL(255),
	price VARCHAR NOT NULL(255),
	condition VARCHAR NOT NULL(255),
	image_url VARCHAR NOT NULL(255)
);